spring:
  h2:
    console:
      path: /h2-console
  datasource:
    username: admin
    password:
    url: jdbc:h2:mem:test;MODE=MYSQL
  liquibase:
    change-log: classpath:db/master.xml
  jpa:
    show-sql: true
